# -*- coding: utf-8 -*-
"""tupla.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11J1XR5DelGkm7ur4YkgFdcNUTYXJnCf9
"""

tupli=lambda*tupla:sum(tupla);tupla=map(int,input("Insira a tupla separada por virgula(,):\n").split(","));print("\nR:",tupli(*tupla))